services:
  app:
    build:
      target: dev
      args:
        - APP_PORT=${APP_PORT:-3000}
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    environment:
      - APP_PORT=${APP_PORT:-3000}
    volumes:
      - .:/app
      - /app/node_modules
    restart: no
